[{{ app_name }}]
user  = www-data
group = www-data
listen = /run/php/{{ app_name }}.sock
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children      = 5
pm.start_servers     = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3
security.limit_extensions = .php

php_admin_value[upload_max_filesize] = {{ ureport_client_max_image_size }}
php_admin_value[post_max_size]       = {{ ureport_client_max_image_size }}

env[SITE_HOME] = {{ ureport_client_site_home }}
