---
- hosts: "ureport_client"
  become: "yes"
  roles:
    - "City-of-Bloomington.php"

  tasks:
    - name: "Create directories"
      ansible.builtin.file:
        path: "{{ item }}"
        state: "directory"
        owner: "www-data"
        group: "staff"
        mode:  "u=rwX,g=rwXs,o=rX"
      with_items:
        - "{{ ureport_client_install_path }}"
        - "{{ ureport_client_site_home    }}"
        - "{{ ureport_client_site_home    }}/sessions"

    - name: "Extract release"
      ansible.builtin.unarchive:
        src:  "{{ ureport_client_archive_path }}"
        dest: "{{ ureport_client_install_path | dirname }}"
      register: "release"

    - name: "Apache configuration"
      ansible.builtin.template:
        src:  "apache.conf"
        dest: "/etc/apache2/sites-enabled/conf.d/ureport_client.conf"
      notify: "apache_restart"

    - name: "Install site_config"
      ansible.builtin.template:
        src:  "site_config.j2"
        dest: "{{ ureport_client_site_home }}/site_config.php"

    - name: 'Update directory permissions'
      ansible.builtin.file:
        path:    "{{ item }}"
        state:   'directory'
        owner:   'www-data'
        group:   'staff'
        mode:    'u=rwX,g=rwX,o=rX'
        recurse: 'true'
      with_items:
        - "{{ ureport_client_install_path }}"
        - "{{ ureport_client_site_home    }}"
...
